name: bankmanagement
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
  -  assets/images/
  -  assets/svg/

